### ISSUE TITLE
Broken reports due to casing change

### ISSUE THREAD

**Issue by hgGeorg** [jsreport/jsreport-dotnet-shared#2]
In prior versions of jsreport properties were always camelCased. But due to changes in [this commit](https://github.com/jsreport/jsreport-dotnet-shared/commit/c315414824ba03ccad8b826888a14a2a415f5046) properties are now cased the same as the .net model (which are PascalCased). This discrepancy broke all our existing reports. Some of them thousands of lines big, spread over multiple separate files.

I'm pleading for either reverting this change or a way to configure the ContractResolver ourselves.

**Comment by pofider** [comment]
Sorry to hear that. My apologies. Unfortunately, this was a bug but that had to be fixed.
I take a look if we can make it configurable for you now.

**Comment by hgGeorg** [comment]
Thank you for your quick response. We will revert to an older version of jsreport for now.

**Comment by pofider** [comment]
I hve the changes ready. I wanted to double-check it here with you before I push it. 

The custom contract resolver for data property can be passed to both `jsreport.Local`
```csharp
new LocalReporting()
                .UseBinary(JsReportBinary.GetBinary())
                .UseContractResolverForDataProperty(new CamelCasePropertyNamesContractResolver())
                .AsUtility()
                .Create();
```

As well as to `jsreport.Client`
```csharp
new ReportingService("http://localhost:5488")  {
    ContractResolverForDataProperty = new CamelCasePropertyNamesContractResolver()
}
```

This should work as back-compatibility flag and is applied just globally for all rendering requests called on the particular `IRenderService` instance. Is this fine for you?

**Comment by hgGeorg** [comment]
Hi, sorry for my late answer.

Yes, this seems fine to me.

Thank you very much.

**Comment by pofider** [comment]
This is now released in
jsreport.Client@3.1.0
jsreport.Local@2.3.0

I apologize for your original troubles.
